-- Disable RLS temporarily to test connection
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE elections DISABLE ROW LEVEL SECURITY;
ALTER TABLE candidates DISABLE ROW LEVEL SECURITY;
ALTER TABLE votes DISABLE ROW LEVEL SECURITY;